# Generated by Django 5.2.9 on 2025-12-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="juego",
            name="imagen",
            field=models.CharField(default="default.jpg", max_length=200),
        ),
    ]
