# Generated by Django 5.2.9 on 2025-12-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0002_juego_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="juego",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="juegos/"),
        ),
    ]
