# Generated by Django 5.2.9 on 2025-12-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrito", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcarrito",
            name="carrito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="carrito.carrito",
            ),
        ),
    ]
